# Generated by Django 5.2.8 on 2025-11-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_aluno_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadedados',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Altura (m)'),
        ),
        migrations.AlterField(
            model_name='fichadedados',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (Kg)'),
        ),
    ]
