# Generated by Django 5.2.8 on 2025-11-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_fichadedados_altura_alter_fichadedados_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadedados',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
